test_cv_answers = [
    {"role": "user", "content": "Dominik Ružić"},
    {"role": "assistant", "content": "Koja je vaša adresa stanovanja?"},
    {"role": "user", "content": "Kneza Mislava 3, 52100 Pula, Hrvatska"},
    {"role": "assistant", "content": "Koji je vaš email?"},
    {"role": "user", "content": "ruzicdominik11@gmail.com"},
    {"role": "assistant", "content": "Koji je vaš broj telefona?"},
    {"role": "user", "content": "+385 99 850 5024"},
    {"role": "assistant", "content": "Koji je vaš link github profila?"},
    {"role": "user", "content": "https://github.com/druzic"},
    {"role": "assistant", "content": "Koliko obrazovnih kvalifikacija imate?"},
    {"role": "user", "content": "2"},
    {"role": "assistant", "content": "Naziv institucije?"},
    {"role": "user", "content": "FIPU"},
    {"role": "assistant", "content": "Stečena titula ili program?"},
    {"role": "user", "content": "Diplomski sveučilišni studij Informatika"},
    {"role": "assistant", "content": "Datum početka?"},
    {"role": "user", "content": "Lis 2022"},
    {"role": "assistant", "content": "Datum završetka?"},
    {"role": "user", "content": "Lip 2025"},
    {"role": "assistant", "content": "Relevantni kolegiji?"},
    {"role": "user", "content": "Raspodijeljeni sustavi, Mobilne aplikacije, Neuronske mreže i duboko učenje, Napredni algoritmi i strukture podataka, Internet stvari"},
    {"role": "assistant", "content": "Naziv institucije?"},
    {"role": "user", "content": "Sveučilište Jurja Dobrile u Puli, Fakultet informatike u Puli"},
    {"role": "assistant", "content": "Stečena titula ili program?"},
    {"role": "user", "content": "Prijediplomski sveučilišni studij Informatika"},
    {"role": "assistant", "content": "Datum početka?"},
    {"role": "user", "content": "Lis 2019"},
    {"role": "assistant", "content": "Datum završetka?"},
    {"role": "user", "content": "Ruj 2022"},
    {"role": "assistant", "content": "Relevantni kolegiji?"},
    {"role": "user", "content": "Osnove IKT, Strukture podataka i algoritama, Baze podataka, Napredne tehnike programiranja, Programsko inženjerstvo, Web aplikacije"},
    {"role": "assistant", "content": "Koliko radnih iskustava imate?"},
    {"role": "user", "content": "2"},
    {"role": "assistant", "content": "Naziv pozicije?"},
    {"role": "user", "content": "Wordpress SEO administrator"},
    {"role": "assistant", "content": "Naziv tvrtke?"},
    {"role": "user", "content": "Lescan Digital"},
    {"role": "assistant", "content": "Datum početka?"},
    {"role": "user", "content": "Tra 2022"},
    {"role": "assistant", "content": "Datum završetka?"},
    {"role": "user", "content": "Svi 2022"},
    {"role": "assistant", "content": "Opis radnog mjesta?"},
    {"role": "user", "content": "Wordpress SEO administracija"},
    {"role": "assistant", "content": "Naziv pozicije?"},
    {"role": "user", "content": "Web CMS developer"},
    {"role": "assistant", "content": "Naziv tvrtke?"},
    {"role": "user", "content": "Tri M"},
    {"role": "assistant", "content": "Datum početka?"},
    {"role": "user", "content": "Lip 2021"},
    {"role": "assistant", "content": "Datum završetka?"},
    {"role": "user", "content": "Ruj 2021"},
    {"role": "assistant", "content": "Opis radnog mjesta?"},
    {"role": "user", "content": "Razvoj web CMS sustava za administraciju."},
    {"role": "assistant", "content": "Koje vještine imate (tehničke, softverske, itd.)?"},
    {"role": "user", "content": "Vue.js, Node.js (Express), React.js, Python (FastAPI, Tensorflow), Android razvoj (Java i Flutter), C++, Git, MongoDB, Firebase, PostgreSQL"},
    {"role": "assistant", "content": "Koje jezike govorite?"},
    {"role": "user", "content": "hrvatski (materinji), engleski (B2)"},
    {"role": "assistant", "content": "Imate li projekte koje želite navesti?"},
    {"role": "user", "content": "Da"},
    {"role": "assistant", "content": "Naziv projekta?"},
    {"role": "user", "content": "E-commerce platforma"},
    {"role": "assistant", "content": "Opis projekta?"},
    {"role": "user", "content": "Izrada e-commerce platforme koristeći Vue.js i Node.js"},
    {"role": "assistant", "content": "Link na projekt?"},
    {"role": "user", "content": "https://github.com/druzic"},
    {"role": "assistant", "content": "Naziv projekta?"},
    {"role": "user", "content": "3D igra u Unityu"},
    {"role": "assistant", "content": "Opis projekta?"},
    {"role": "user", "content": "Razvoj 3D igre u timu koristeći Unity engine"},
    {"role": "assistant", "content": "Link na projekt?"},
    {"role": "user", "content": "https://github.com/druzic"},
    {"role": "assistant", "content": "Koji su vaši interesi i hobiji?"},
    {"role": "user", "content": "Web i mobilni razvoj, razvoj videoigara, sport"}
]